databases:
  - name: repodoc_ai
    plan: free
    databaseName: repodoc_ai
    user: repodoc_ai

services:
  - type: web
    plan: free
    name: repodoc-ai
    runtime: python
    buildCommand: 'cd mcp_integration && chmod +x build.sh && ./build.sh'
    startCommand: 'cd mcp_integration && chmod +x start_production.sh && ./start_production.sh'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: repodoc_ai
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'repodoc-ai.onrender.com'
      - key: WEB_CONCURRENCY
        value: '2'
      - key: PORT
        value: '10000'
      - key: GITHUB_PERSONAL_ACCESS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false