databases:
  - name: repodoc_ai
    plan: free
    databaseName: repodoc_ai
    user: repodoc_ai

services:
  - type: web
    plan: free
    name: repodoc-ai
    runtime: python
    buildCommand: 'cd mcp_integration && chmod +x build.sh && ./build.sh'
    startCommand: 'cd mcp_integration && source venv/bin/activate && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn mcp_integration.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --max-requests 1000 --max-requests-jitter 100 --preload'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: repodoc_ai
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'repodoc-ai.onrender.com'
      - key: WEB_CONCURRENCY
        value: '2'
      - key: GITHUB_PERSONAL_ACCESS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false