databases:
  - name: repodoc_ai
    plan: free
    databaseName: repodoc_ai
    user: repodoc_ai

services:
  - type: web
    plan: free
    name: mcp_integration
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mcp_integration.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: repodoc_ai
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4