# Generated by Django 4.2.20 on 2025-09-04 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mcp_manager", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GeneratedDocument",
        ),
        migrations.DeleteModel(
            name="GitHubRepository",
        ),
    ]
